-- Regular application data. Keep these tables separate by responsibility.
CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT UNIQUE NOT NULL,            -- Muse login email or mobile number
  phone_number TEXT NOT NULL,                 -- where Photon texts this user
  consent INTEGER NOT NULL DEFAULT 0,         -- agreed to be texted about matches
  device_token_hash TEXT UNIQUE,
  browserbase_context_id TEXT,                -- keeps the Muse login for later prompts
  username TEXT UNIQUE,                       -- Instagram username, reported by Muse
  name TEXT,
  profile_status TEXT NOT NULL DEFAULT 'pending',  -- pending | ready | error
  profile_error TEXT,
  callback_token TEXT UNIQUE,                 -- single-use; identifies the pending prompt
  prompted_at BIGINT,
  summarized_at BIGINT,
  refresh_error TEXT,
  photon_error TEXT,                          -- why adding this number to Photon's Users list failed
  photon_line TEXT,                           -- the Photon number this person must text once first
  first_text_at BIGINT,                      -- when the app reported sending that first text
  texts_confirmed_at BIGINT,                 -- when the "match texts are on" text was delivered to Photon
  summary TEXT,                               -- copy of the Instagram summary Muse wrote (shown in developer mode)
  use_dms INTEGER NOT NULL DEFAULT 0,         -- include reels shared in Instagram messages
  created_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS logins (
  id TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  consent INTEGER NOT NULL,
  auto_approve INTEGER NOT NULL DEFAULT 0,  -- user ticked "approve Muse's access to this server for me"
  use_dms INTEGER NOT NULL DEFAULT 0,       -- user ticked "include reels from my Instagram messages"
  session_id TEXT NOT NULL,
  connect_url TEXT NOT NULL,
  context_id TEXT NOT NULL,
  step TEXT NOT NULL,
  busy INTEGER NOT NULL DEFAULT 0,
  expires BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS setup_checks (
  token TEXT PRIMARY KEY,                     -- in the setup-check prompt
  received_at BIGINT                          -- when Muse's test POST arrived
);
CREATE TABLE IF NOT EXISTS sightings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  me TEXT NOT NULL,
  other TEXT NOT NULL,
  seen_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS sightings_pair ON sightings (me, other, seen_at);
CREATE TABLE IF NOT EXISTS scores (
  pair TEXT PRIMARY KEY,                      -- "a|b" with a < b
  profile_a INTEGER NOT NULL,                 -- taste_profile ids
  profile_b INTEGER NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  verdict TEXT NOT NULL,
  scored_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair TEXT NOT NULL,
  username TEXT NOT NULL,                     -- recipient
  status TEXT NOT NULL,                       -- sent | failed
  message_id TEXT,
  error TEXT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS notifications_pair ON notifications (pair, created_at);

CREATE TABLE IF NOT EXISTS taste_profile (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, username TEXT UNIQUE NOT NULL, summary TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS match_result (
  profile_a INTEGER NOT NULL REFERENCES taste_profile(id),
  profile_b INTEGER NOT NULL REFERENCES taste_profile(id),
  score DOUBLE PRECISION NOT NULL, verdict TEXT NOT NULL,
  PRIMARY KEY (profile_a, profile_b)
);

-- Vector storage. Summary text stays alongside each embedding for identification.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id TEXT PRIMARY KEY,
  summary_text TEXT NOT NULL,
  embedding VECTOR(384)
);
