/* eslint-disable @typescript-eslint/no-require-imports -- One-time CommonJS source conversion utility. */
const fs = require('node:fs');
const ts = require('typescript');
let source = fs.readFileSync('lib/db.ts', 'utf8');
const schemaMatch = source.match(/const SCHEMA = `([\s\S]*?)`;/);
if (!schemaMatch) { console.log('Neon source conversion already completed. Use npm run db:setup.'); process.exit(0); }
let schema = schemaMatch[1];
schema = schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/(\w+_at|expires) INTEGER/g, '$1 BIGINT');
schema += `\nCREATE TABLE IF NOT EXISTS taste_profile (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, username TEXT UNIQUE NOT NULL, summary TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS match_result (
  profile_a INTEGER NOT NULL REFERENCES taste_profile(id),
  profile_b INTEGER NOT NULL REFERENCES taste_profile(id),
  score DOUBLE PRECISION NOT NULL, verdict TEXT NOT NULL,
  PRIMARY KEY (profile_a, profile_b)
);\n`;
fs.mkdirSync('database', {recursive:true});
fs.writeFileSync('database/schema.sql', schema.trim()+'\n');
source = source.slice(source.indexOf('export type Account'));
const start = source.indexOf('const globalState');
const end = source.indexOf('export const hashToken');
source = source.slice(0,start) + `/** Async prepared queries; values are always bound separately from SQL. */
export function db() {
  return {
    prepare(query: string) {
      let index = 0;
      const sql = query.replace(/\\?/g, () => '$' + (++index));
      return {
        async get(...values: unknown[]) { return (await database().query(sql, values))[0]; },
        async all(...values: unknown[]) { return await database().query(sql, values); },
        async run(...values: unknown[]) {
          const result = await database().query(sql, values, { fullResults: true });
          return { changes: result.rowCount };
        },
      };
    },
  };
}

` + source.slice(end);
fs.writeFileSync('lib/db.ts', `// Server-only Neon Postgres storage for accounts, sessions and matching state.
import { createHash, randomBytes } from 'node:crypto';
import { database } from './neon';
\n`+source);
// Convert the full dependency chain to async, preserving existing formatting.
const names = new Set(['accountByToken','accountById','accountByUsername','accountByCallbackToken','upsertAccount','requireAccount','loginById','setStep','setBusy','beginPrompt','failIfTimedOut','wasNotified','matchesFor','resetDemo','arrived']);
const files = [];
function walk(dir) { for(const ent of fs.readdirSync(dir,{withFileTypes:true})) {const p=dir+'/'+ent.name; if(ent.isDirectory()) walk(p); else if(p.endsWith('.ts')) files.push(p);} }
walk('lib'); walk('app/api');
for(const file of files) {
 let text=fs.readFileSync(file,'utf8').replaceAll('./spacetime','./profiles').replaceAll('@/lib/spacetime','@/lib/profiles');
 const sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true);
 const edits=[];
 function visit(node) {
   if(ts.isCallExpression(node)) {
     const expr=node.expression;
     const target=ts.isIdentifier(expr)&&names.has(expr.text);
     const dbCall=ts.isPropertyAccessExpression(expr)&&['get','all','run'].includes(expr.name.text)&&expr.expression.getText(sf).startsWith('db().prepare(');
     if((target||dbCall)&&!ts.isAwaitExpression(node.parent)) { edits.push([node.getStart(sf),node.getStart(sf),'(await '],[node.end,node.end,')']); }
   }
   if((ts.isFunctionDeclaration(node)||ts.isArrowFunction(node))&&node.body) {
     const named=ts.isFunctionDeclaration(node)&&node.name&&names.has(node.name.text);
     const arrow=ts.isArrowFunction(node)&&ts.isVariableDeclaration(node.parent)&&names.has(node.parent.name.getText(sf));
     const map=ts.isArrowFunction(node)&&ts.isCallExpression(node.parent)&&node.parent.expression.getText(sf)==='rows.map';
     if((named||arrow||map)&&!node.modifiers?.some(m=>m.kind===ts.SyntaxKind.AsyncKeyword)) {
       const pos=ts.isFunctionDeclaration(node)?node.getStart(sf)+(node.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword)?7:0):node.getStart(sf);
       edits.push([pos,pos,'async ']);
       if(node.type) edits.push([node.type.getStart(sf),node.type.end,'Promise<'+node.type.getText(sf)+'>']);
     }
   }
   ts.forEachChild(node,visit);
 }
 visit(sf);
 edits.sort((a,b)=>b[0]-a[0]);
 for(const [a,b,value] of edits) text=text.slice(0,a)+value+text.slice(b);
 if(file==='lib/matching.ts') text=text.replace('return rows.map(async score => {','return Promise.all(rows.map(async score => {').replace('  });\n}\n\n/**\n * Restarts','  }));\n}\n\n/**\n * Restarts');
 fs.writeFileSync(file,text);
}
